Thinking in vectors

In [11]:
numbers = range(1, 5)

squared = [n**2 for n in numbers]

print(squared)

# or maybe...

import numpy as np

numbers = np.array(range(1, 5))

squared = numbers ** 2

print(squared)

[1, 4, 9, 16]
[ 1  4  9 16]


In [14]:
numbers = np.array(range(1, 11))

by_5 = numbers * 5

mean = np.mean(by_5) # sum(by_5) / numbers.size

print(mean)

27.5


In [18]:
arr = np.arange(100)

even = arr[arr % 2 == 0]

squared = even ** 2

mean = np.mean(squared)

print(mean)

3234.0


Identifying a circle...

In [58]:
import numpy as np

img = np.zeros((10, 10))

img[3,4] = 1
img[4,3] = 1
img[4,4] = 1
img[4,5] = 1
img[5,4] = 1

print(img)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [1]:
def relu(x):
    return max(0, x)

def neuron(x1, x2, w1, w2, b):
    return w1*x1 + w2*x2 + b

def hidden_layer(x, y):
    h1 = relu(neuron(x, y, 1, 0, 0))      # |
    h2 = relu(neuron(x, y, 0, 1, 0))      # _
    h3 = relu(neuron(x, y, -1, -1, 5))    # /
    return h1, h2, h3

def output_layer(h1, h2, h3):
    return h1 + h2 + h3

points = [
    (0, 0),
    (2, 2),
    (4, 4),
    (5, 0),
]

for p in points:
    h = hidden_layer(p[0], p[1])
    out = output_layer(*h)
    print(p, "->", out)

(0, 0) -> 5
(2, 2) -> 5
(4, 4) -> 8
(5, 0) -> 5
